# 國小視力不良統計資料(100學年度~109學年度)
    資料來源：https://www.stat.gov.tw/Statistics.aspx?n=2978&CaN=295
    因使用ods檔，需先 pip install odfpy

## 1.匯入資料

In [112]:
import pandas as pd

pd.read_excel('~/Desktop/github/LAT-Repo/2023 03 08(week3 work)/W3 homework.ods', engine='odf')

,項目,全國,Unnamed: 2,Unnamed: 3,公立,Unnamed: 5,Unnamed: 6,私立,Unnamed: 8,Unnamed: 9
0,學年度,平均,男,女,平均,男,女,平均,男,女
1,100,50.01,48.89,51.24,49.95,48.84,51.17,52.46,51.03,54.17
2,101,49.361388,48.405038,50.409395,49.291184,48.333063,50.338987,52.240871,51.240744,53.433057
3,102,48.10794,47.331407,48.959603,48.053444,47.275555,48.90522,50.189699,49.40248,51.108042
4,103,47.052129,46.467743,47.693371,46.974962,46.396574,47.608638,49.78803,48.924585,50.789241
5,104,46.121721,45.508135,46.793976,46.026275,45.411223,46.69939,49.30759,48.685195,50.015191
6,105,45.855873,45.076418,46.707088,45.780815,45.005549,46.626942,48.236085,47.302684,49.275191
7,106,45.478238,44.63659,46.396042,45.41818,44.569997,46.342784,47.286357,46.630966,48.00871
8,107,44.788008,43.835774,45.821373,44.739549,43.789502,45.770716,46.182861,45.170921,47.275658
9,108,44.33,43.39,45.35,44.340803,43.394221,45.365693,44.627466,43.47951,45.850548
10,109,44.552649,43.604685,45.574055,44.512417,43.586382,45.511182,45.653445,44.112327,47.269642

## 2.選擇資料中的國小視力不良率-縣市表

In [70]:
pd.read_excel("W3 homework.ods", sheet_name="國小視力不良率-縣市")

,學年度,基隆市,臺北市,新北市,桃園縣(市),新竹市,新竹縣,苗栗縣,臺中市,南投縣,...,嘉義縣,臺南市,高雄市,屏東縣,宜蘭縣,花蓮縣,臺東縣,澎湖縣,金門縣,連江縣
0,100,52.950000,52.390000,54.630000,49.540000,49.730000,46.720000,43.900000,53.300000,42.230000,...,41.470000,49.590000,51.160000,38.840000,43.340000,36.360000,31.270000,41.590000,44.150000,45.510000
1,101,50.870000,51.560000,53.430000,49.460000,49.400000,46.170000,44.130000,52.510000,42.370000,...,41.920000,49.490000,50.310000,37.850000,43.440000,37.270000,31.030000,42.050000,44.810000,49.040000
2,102,48.440000,50.420000,51.110000,48.930000,48.240000,46.370000,42.920000,51.270000,40.970000,...,40.930000,47.820000,48.420000,36.900000,42.310000,37.750000,29.660000,42.420000,44.390000,44.010000
3,103,47.021158,49.437483,49.910578,49.204327,45.924749,45.231322,41.120166,49.552625,40.513202,...,41.557204,46.444270,46.442814,37.164614,40.684140,38.228262,29.127540,42.372479,41.600438,43.404255
4,104,46.314511,47.921203,49.107343,39.926550,45.993894,44.789013,41.837900,48.084614,40.055151,...,40.811125,48.369704,45.735997,36.713924,45.151867,37.784918,28.517655,42.272727,43.036250,39.909297
5,105,46.513452,47.049203,48.712291,39.165242,44.885512,44.847973,42.146146,48.171283,39.131156,...,41.955684,48.271714,45.411810,36.666934,44.973610,37.079361,27.678655,42.830441,39.534239,45.555556
6,106,47.132436,46.024006,48.188869,38.449706,44.820095,44.500042,42.277015,46.996310,39.411333,...,41.571999,47.935234,44.803180,37.474662,44.727484,36.573107,26.048799,42.308786,38.831996,40.421053
7,107,46.277603,44.546728,47.541135,46.124896,43.695943,43.820813,42.957899,47.541726,39.003693,...,41.408843,44.033439,44.383320,36.896001,38.365632,36.554317,25.216621,40.881590,35.382550,42.259414
8,108,47.130000,43.580000,46.570000,47.460000,42.010000,44.540000,43.720000,44.050000,37.750000,...,39.850000,43.700000,38.930000,36.310000,46.080000,36.850000,25.400000,40.560000,35.760000,41.880000
9,109,47.380586,43.907165,46.527595,46.060311,42.366400,44.997716,44.545058,47.755525,37.861363,...,40.334615,43.980000,43.920588,36.793006,39.674669,37.451123,26.253203,40.923707,36.702831,41.140530

#### 第一題
    問：哪個縣市的哪年度學生視力不良率最高/最低？

最高值為 54.63，所在的縣市為 新北市，所在的學年度為 100

In [91]:
import pyexcel_ods3

# 打开ODS文件
data = pyexcel_ods3.get_data("W3 homework.ods")

# 获取第一个工作表的数据
sheet_data = data['國小視力不良率-縣市']

# 读取第一行和第一列的数据
year = []
city = []
if len(sheet_data) > 0:
    row1 = sheet_data[0]
    year = row1[1:] if len(row1) > 1 else []
if len(sheet_data) > 1:
    col1 = sheet_data[1]
    city = [row[0] for row in sheet_data[1:] if len(row) > 0]

# 初始化最大值和最大值列表
max_value = None
max_rows = []
max_columns = []

# 遍历每一列并比较最大值
for i, column in enumerate(sheet_data):
    # 跳过第一列
    if i == 0:
        continue
    # 初始化当前列的数字值列表和行号列表
    values = []
    rows = []
    # 遍历当前列的单元格
    for j, value in enumerate(column):
        # 跳过第一行
        if j == 0:
            continue
        # 将每个值转换为数字类型
        try:
            value = float(value)
            values.append(value)
            rows.append(j)
        except ValueError:
            pass
    # 获取当前列的最大值
    if len(values) > 0:
        current_max = max(values)
        # 如果当前列的最大值大于前面的最大值，更新最大值和最大值列表
        if max_value is None or current_max > max_value:
            max_value = current_max
            max_columns = [i]
            max_rows = [rows[k] for k in range(len(values)) if values[k] == current_max]
        # 如果当前列的最大值等于前面的最大值，将列号和行号添加到最大值列表中
        elif current_max == max_value:
            max_columns.append(i)
            max_rows.extend([rows[k] for k in range(len(values)) if values[k] == current_max])

# 输出最大值所在的学年度和县市
if max_value is not None and len(max_rows) > 0 and len(max_columns) > 0:
    year_str = ", ".join([year[row-1] for row in max_rows if row > 0 and row <= len(year)])
    city_str = ", ".join([str(city[col-1]) for col in max_columns if col > 0 and col-1 < len(city)])
    print("最大值為 {}，所在的縣市為 {}，所在的學年度為 {}".format(max_value, year_str, city_str))
else:
    print("數據為空，無法獲取最大值所在的學年度和縣市。")

最大值為 54.63，所在的縣市為 新北市，所在的學年度為 100

最低值為 25.2166207168176，所在的縣市為 臺東縣，所在的學年度為 100

In [89]:
import pyexcel_ods3

# 打开ODS文件
data = pyexcel_ods3.get_data("W3 homework.ods")

# 获取第一个工作表的数据
sheet_data = data['國小視力不良率-縣市']

# 读取第一行和第一列的数据
year = []
city = []
if len(sheet_data) > 0:
    row1 = sheet_data[0]
    year = row1[1:] if len(row1) > 1 else []
if len(sheet_data) > 1:
    col1 = sheet_data[1]
    city = [row[0] for row in sheet_data[1:] if len(row) > 0]

# 初始化最小值和最小值列表
min_value = None
min_rows = []
min_columns = []

# 遍历每一列并比较最小值
for i, column in enumerate(sheet_data):
    # 跳过第一列
    if i == 0:
        continue
    # 初始化当前列的数字值列表和行号列表
    values = []
    rows = []
    # 遍历当前列的单元格
    for j, value in enumerate(column):
        # 跳过第一行
        if j == 0:
            continue
        # 将每个值转换为数字类型
        try:
            value = float(value)
            values.append(value)
            rows.append(j)
        except ValueError:
            pass
    # 获取当前列的最小值
    if len(values) > 0:
        current_min = min(values)
        # 如果当前列的最小值小于前面的最小值，更新最小值和最小值列表
        if min_value is None or current_min < min_value:
            min_value = current_min
            min_columns = [i]
            min_rows = [rows[k] for k in range(len(values)) if values[k] == current_min]
        # 如果当前列的最小值等于前面的最小值，将列号和行号添加到最小值列表中
        elif current_min == min_value:
            min_columns.append(i)
            min_rows.extend([rows[k] for k in range(len(values)) if values[k] == current_min])

# 输出最小值所在的学年度和县市
if min_value is not None and len(min_rows) > 0 and len(min_columns) > 0:
    year_str = ", ".join([str(year[row-1]) for row in min_rows if row > 0 and row <= len(year)])
    city_str = ", ".join([str(city[col-1]) for col in max_columns if col > 0 and col-1 < len(city)])
    print("最小值為 {}，所在的縣市為 {}，所在的學年度為 {}".format(min_value, year_str, city_str))
else:
    print("數據為空，無法獲取最小值所在的學年度和縣市。")

最小值為 25.2166207168176，所在的縣市為 臺東縣，所在的學年度為 100

#### 第二題
    問：各縣市的學生視力不良率是否呈現逐年攀升？

計算各縣市成長率(資料只有匯出至雲林縣)

In [9]:
import ezodf

# 讀取 ods 檔案
doc = ezodf.opendoc('W3 homework.ods')

# 選擇要分析的工作表
sheet = doc.sheets['國小視力不良率-縣市']

# 讀取縣市名稱和學年度
cities = [cell.value for cell in sheet.column(0)[1:]]
years = [cell.value for cell in sheet.row(0)[1:]]

# 讀取不良率數據
data = []
growth_rates = []  # 添加一个空的列表以确保与城市相对应的子列表存在
for row in list(sheet.rows())[1:]:
    data_row = []
    for cell in row[1:]:
        if cell.value is not None:
            data_row.append(float(cell.value))
        else:
            data_row.append(None)
    data.append(data_row)
    growth_rates.append([])  # 添加一个空的子列表

# 計算成長率
for i, city_data in enumerate(data):
    for j in range(len(years) - 1):
        if city_data[j] is not None and city_data[j+1] is not None:
            growth_rate = (city_data[j+1] - city_data[j]) / city_data[j] * 100
            growth_rates[i].append(growth_rate)
        else:
            growth_rates[i].append(None)
    # 確保 growth_rates[i] 至少有 len(years) - 1 個元素
    while len(growth_rates[i]) < len(years) - 1:
        growth_rates[i].append(None)

# 列出結果
print("縣市名稱\t\t", end="")
for year in years[1:]:
    print(f"{year}\t", end="")
print()
print("="*70)

for i, city in enumerate(cities):
    print(f"{city}\t", end="")
    if len(growth_rates[i]) < len(years) - 1:
        growth_rates[i] += [None] * (len(years) - 1 - len(growth_rates[i]))
    for j, year in enumerate(years):
        if j == 0:
            continue
        if growth_rates[i][j-1] is not None:
            print(f"{growth_rates[i][j-1]:.2f}%\t", end="")
        else:
            print("N/A\t", end="")
    print()

縣市名稱		臺北市	新北市	桃園縣(市)	新竹市	新竹縣	苗栗縣	臺中市	南投縣	彰化縣	雲林縣	嘉義市	嘉義縣	臺南市	高雄市	屏東縣	宜蘭縣	花蓮縣	臺東縣	澎湖縣	金門縣	連江縣	None
======================================================================
100.0	-1.06%	4.28%	-9.32%	0.38%	-6.05%	-6.04%	21.41%	-20.77%	24.70%	-14.76%	20.25%	-23.18%	19.58%	3.17%	-24.08%	11.59%	-16.11%	-14.00%	33.00%	6.16%	3.08%	N/A
101.0	1.36%	3.63%	-7.43%	-0.12%	-6.54%	-4.42%	18.99%	-19.31%	21.86%	-14.70%	17.92%	-19.28%	18.06%	1.66%	-24.77%	14.77%	-14.20%	-16.74%	35.51%	6.56%	9.44%	N/A
102.0	4.09%	1.37%	-4.27%	-1.41%	-3.88%	-7.44%	19.45%	-20.09%	25.48%	-15.85%	21.38%	-22.05%	16.83%	1.25%	-23.79%	14.66%	-10.78%	-21.43%	43.02%	4.64%	-0.86%	N/A
103.0	5.14%	0.96%	-1.42%	-6.67%	-1.51%	-9.09%	20.51%	-18.24%	24.11%	-15.99%	24.16%	-20.76%	11.76%	-0.00%	-19.98%	9.47%	-6.04%	-23.81%	45.47%	-1.82%	4.34%	N/A
104.0	3.47%	2.48%	-18.70%	15.20%	-2.62%	-6.59%	14.93%	-16.70%	19.01%	-9.90%	19.85%	-20.71%	18.52%	-5.44%	-19.73%	22.98%	-16.32%	-24.53%	48.23%	1.81%	-7.27%	N/A
105.0	1.15%	3.53%	-19.60%	14.61%	-0.08%	-6.02%	14.30%	-18.77%	21.37%	-10.55%	19.25%	-17.19%	15.05%	-5.92%	-19.26%	22.65%	-17.55%	-25.35%	54.74%	-7.70%	15.23%	N/A
106.0	-2.35%	4.70%	-20.21%	16.57%	-0.71%	-5.00%	11.16%	-16.14%	21.07%	-8.54%	16.59%	-18.30%	15.31%	-6.53%	-16.36%	19.35%	-18.23%	-28.78%	62.42%	-8.22%	4.09%	N/A
107.0	-3.74%	6.72%	-2.98%	-5.27%	0.29%	-1.97%	10.67%	-17.96%	18.96%	-7.58%	14.00%	-15.30%	6.34%	0.79%	-16.87%	3.98%	-4.72%	-31.02%	62.12%	-13.45%	19.44%	N/A
108.0	-7.53%	6.86%	1.91%	-11.48%	6.02%	-1.84%	0.75%	-14.30%	19.42%	-6.41%	17.14%	-19.36%	9.66%	-10.92%	-6.73%	26.91%	-20.03%	-31.07%	59.69%	-11.83%	17.11%	N/A
109.0	-7.33%	5.97%	-1.00%	-8.02%	6.21%	-1.01%	7.21%	-20.72%	19.73%	-5.26%	14.03%	-17.63%	9.04%	-0.14%	-16.23%	7.83%	-5.60%	-29.90%	55.88%	-10.31%	12.09%	N/A
None	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A	N/A

#### 第三題
    問：100學年~109學年哪種性別的平均視力不良率較嚴重？

#### 第四題
    問：全國的公私立學校學生哪種校別的視力不良率較低？

#### 第五題
    問：哪些縣市的學生視力不良率呈現逐年攀升？其中以哪一個縣市最為明顯？

#### 第六題
    問：哪些縣市的學生視力不良率呈現逐年攀升？其中以哪一個縣市最為明顯？

#### 第七題
    問：哪些縣市的學生視力不良率呈現逐年攀升？其中以哪一個縣市最為明顯？

#### 第八題
    問：哪些縣市的學生視力不良率呈現逐年攀升？其中以哪一個縣市最為明顯？